FROM zabbix/zabbix-web-service:ubuntu-7.2.1

RUN apt update && apt install -y wget gnupg \
    && wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' \
    && apt update && apt install -y google-chrome-stable \
    && apt clean && rm -rf /var/lib/apt/lists/*

CMD ["/usr/sbin/zabbix_web_service", "-f"]