services:
  # zabbix-proxy:
  #   image: zabbix/zabbix-proxy-mysql:ubuntu-7.2.1
  #   container_name: zabbix-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "10052:10051" # Zabbix Proxy port
  #   environment:
  #     ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
  #     ZBX_SERVER_PORT: ${ZBX_SERVER_PORT}
  #     DB_SERVER_HOST: mysql
  #     ZBX_HOSTNAME: ${ZBX_HOSTNAME_PROXY}
  #     DB_SERVER_PORT: 3306
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     ZBX_ENABLEREMOTECOMMANDS: 1
  #   env_file:
  #     - .env
  #   networks:
  #     - network-datn

  # mysql: # Changed from postgres
  #   image: mysql:8.0 # Using MySQL 8.0 as a stable version
  #   container_name: mysql
  #   restart: unless-stopped
  #   ports:
  #     - "3306:3306" # MySQL default port
  #   volumes:
  #     - mysql:/var/lib/mysql # Changed volume name from postgres to mysql
  #   environment:
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   networks:
  #     - network-datn

  zabbix-server:
    image: "zabbix/zabbix-server-pgsql:ubuntu-7.2.1"
    container_name: server
    restart: unless-stopped
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_WEBSERVICEURL: ${ZBX_WEBSERVICEURL}
      ZBX_STARTREPORTWRITERS: 1 # Enable Report Manager
    depends_on:
      - postgres
    networks:
      - network-datn

  zabbix-web-service:
    image: zabbix/zabbix-web-service:ubuntu-7.2.1
    container_name: web-service
    restart: unless-stopped
    ports:
      - "10053:10053"
    environment:
      ZBX_WEBSERVICE_LISTENPORT: ${ZBX_WEBSERVICE_LISTENPORT}
      ZBX_ALLOWEDIP: ${ZBX_ALLOWEDIP}
      ZBX_CHROMEBIN: "/usr/bin/chromium"
      ZBX_WEBSERVICE_TIMEOUT: 600
    networks:
      - network-datn

  zabbix-frontend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-7.2.1
    restart: unless-stopped
    container_name: frontend
    ports:
      - "8080:8080"
      - "8443:8443"
    # platform: linux/amd64
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PHP_TZ: ${TZ}
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      ZBX_SERVER_PORT: ${ZBX_SERVER_PORT}
      ZBX_SERVER_NAME: ${ZBX_SERVER_NAME}
    depends_on:
      - zabbix-server
    # volumes:
    #   - ./frontend:/usr/share/zabbix
    networks:
      - network-datn

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data/pgdata
    networks:
      - network-datn

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - network-datn

volumes:
  postgres: {}
  mysql: {}

networks:
  network-datn:
    driver: bridge
