FROM zabbix/zabbix-web-nginx-pgsql:ubuntu-7.2.1

# Rename the existing Zabbix frontend directory
RUN mv /usr/share/zabbix /usr/share/zabbix-old || true

# Create a new empty directory for the custom frontend
RUN mkdir -p /usr/share/zabbix

# Copy the custom frontend files into the container
COPY zabbix-frontend /usr/share/zabbix

# Keep the default entrypoint
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]