services:
  # zabbix-server:
  #   image: 'zabbix/zabbix-server-pgsql:ubuntu-7.2.1'
  #   container_name: server
  #   restart: unless-stopped
  #   ports:
  #     - '10051:10051'
  #   environment:
  #     DB_SERVER_HOST: postgres
  #     DB_SERVER_PORT: 5432
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     ZBX_WEBSERVICEURL: ${ZBX_WEBSERVICEURL}
  #     ZBX_STARTREPORTWRITERS: 1 # Enable Report Manager
  #   depends_on:
  #     - postgres
  #   networks:
  #     - network-datn

  # web-service:
  #   image: zabbix/zabbix-web-service:ubuntu-7.2.1
  #   container_name: zabbix-web-service
  #   restart: unless-stopped
  #   ports:
  #     - '10053:10053'
  #   environment:
  #     ZBX_WEBSERVICE_LISTENPORT: 10053
  #     ZBX_ALLOWEDIP: '0.0.0.0/0'
  #     ZBX_CHROMEBIN: '/usr/bin/chromium'
  #     ZBX_WEBSERVICE_TIMEOUT: 600
  #   networks:
  #     - network-datn

  # zabbix-frontend:
  #   image: 'vuong676/tvbix:latest'
  #   restart: unless-stopped
  #   container_name: frontend
  #   ports:
  #     - '80:8080'
  #     - '8443:8443'
  #   environment:
  #     DB_SERVER_HOST: postgres
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     PHP_TZ: ${TZ}
  #     ZBX_SERVER_HOST: zabbix-server
  #     ZBX_SERVER_PORT: 10051
  #     ZBX_SERVER_NAME: 'Camera TVBIX Server'
  #   # volumes:
  #   #   - ./zabbix-frontend:/usr/share/zabbix
  #   depends_on:
  #     - zabbix-server
  #   networks:
  #     - network-datn

  zabbix-proxy:
    image: zabbix/zabbix-proxy-mysql:ubuntu-7.2.1
    container_name: zabbix-proxy
    restart: unless-stopped
    ports:
      - '10052:10051' # Zabbix Proxy port
    environment:
      ZBX_SERVER_HOST: tvbix.xyz
      ZBX_SERVER_PORT: 10051 # Default Zabbix Server port
      DB_SERVER_HOST: mysql
      ZBX_HOSTNAME: zabbix-proxy
      DB_SERVER_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: zabbix_proxy
      ZBX_ENABLEREMOTECOMMANDS: 1

    networks:
      - network-datn

  mysql: # Changed from postgres
    image: mysql:8.0 # Using MySQL 8.0 as a stable version
    container_name: mysql
    restart: unless-stopped
    ports:
      - '3306:3306' # MySQL default port
    volumes:
      - mysql:/var/lib/mysql # Changed volume name from postgres to mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env

    networks:
      - network-datn

  # postgres:
  #   image: postgres:16-alpine
  #   # command: -c ssl=on -c ssl_cert_file=/run/secrets/server-cert.pem -c ssl_key_file=/run/secrets/server-key.pem -c ssl_ca_file=/run/secrets/root-ca.pem
  #   container_name: postgres
  #   restart: unless-stopped
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #     # - pgsql_socket:/var/run/postgresql/
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     PG_DATA: /var/lib/postgresql/data/pgdata
  #   networks:
  #     - network-datn

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: always
  #   ports:
  #     - '9090:8080'
  #   depends_on:
  #     - postgres
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=postgres
  #   networks:
  #     - network-datn

volumes:
  postgres: {}
  mysql: {}

networks:
  network-datn:
    driver: bridge
