export const sampleQuestions = [
  "Thu nhập hàng tháng của tôi đến từ những nguồn nào?",
  "Thu nhập của tôi có đều đặn hàng tháng không?",
  "Có tháng nào thu nhập của tôi tăng đột biến không? Nếu có, tại sao?",
  "Thu nhập của tôi có giảm đột ngột trong tháng nào không? Nếu có, tại sao?",
  "Thu nhập chính của tôi đến từ công việc gì?",
  "Tôi có thu nhập từ đầu tư không? Nếu có, thu nhập này chiếm bao nhiêu phần trăm tổng thu nhập?",
  "Tôi có thu nhập từ kinh doanh không? Nếu có, kinh doanh gì?",
  "Tôi có nhận được khoản tiền thưởng hay tiền hoa hồng nào không?",
  "Tôi có thu nhập từ các khoản tiền cho vay hay tiền lãi tiết kiệm không?",
  "Tổng chi tiêu hàng tháng của tôi là bao nhiêu?",
  "Chi tiêu hàng tháng của tôi được chia thành những loại chi phí nào?",
  "Tôi chi tiêu bao nhiêu tiền cho việc ăn uống mỗi tháng?",
  "Tôi chi tiêu bao nhiêu tiền cho việc mua sắm quần áo mỗi tháng?",
  "Tôi chi tiêu bao nhiêu tiền cho các hoạt động giải trí và du lịch mỗi tháng?",
  "Tôi chi tiêu bao nhiêu tiền cho việc thuê nhà hoặc trả góp nhà?",
  "Tôi chi tiêu bao nhiêu tiền cho các dịch vụ tiện ích như điện, nước, internet?",
  "Tôi chi tiêu bao nhiêu tiền cho việc chăm sóc sức khỏe?",
  "Tôi chi tiêu bao nhiêu tiền cho việc giáo dục (học phí, sách vở)?",
  "Tôi có chi tiêu nào đột biến trong tháng nào không? Nếu có, chi tiêu đó là gì?",
  "Tôi tiết kiệm được bao nhiêu tiền mỗi tháng?",
  "Tôi có kế hoạch tiết kiệm cho những mục tiêu cụ thể không?",
  "Tôi tiết kiệm tiền bằng cách nào? (tài khoản tiết kiệm, đầu tư, quỹ khẩn cấp)",
  "Tôi có đặt mục tiêu tiết kiệm hàng tháng không? Nếu có, mục tiêu đó là bao nhiêu?",
  "Tôi có đạt được mục tiêu tiết kiệm hàng tháng không?",
  "Tôi có kế hoạch tiết kiệm dài hạn không? Nếu có, mục tiêu đó là gì?",
  "Tôi có sử dụng các công cụ hay ứng dụng để theo dõi việc tiết kiệm không?",
  "Tôi có quỹ khẩn cấp không? Nếu có, số tiền trong quỹ đó là bao nhiêu?",
  "Tôi có sử dụng quỹ khẩn cấp trong thời gian gần đây không? Nếu có, tại sao?",
  "Tôi có đầu tư số tiền tiết kiệm không? Nếu có, đầu tư vào đâu?",
  "Tổng số nợ hiện tại của tôi là bao nhiêu?",
  "Tôi có bao nhiêu khoản nợ khác nhau? Các khoản nợ đó là gì?",
  "Số tiền tôi phải trả hàng tháng cho các khoản nợ là bao nhiêu?",
  "Tôi có trả nợ đúng hạn hàng tháng không?",
  "Tôi có khoản nợ nào đang bị trễ hạn không? Nếu có, khoản nợ đó là gì?",
  "Lãi suất của các khoản nợ của tôi là bao nhiêu?",
  "Tôi có kế hoạch trả nợ trong bao lâu?",
  "Tôi có sử dụng thẻ tín dụng không? Nếu có, số dư hiện tại là bao nhiêu?",
  "Tôi có trả hết số dư thẻ tín dụng hàng tháng không?",
  "Tôi có khoản vay sinh viên hoặc vay mua nhà không? Nếu có, số tiền còn lại là bao nhiêu?",
  "Tôi có thực hiện bao nhiêu giao dịch mỗi tháng?",
  "Số tiền trung bình mỗi giao dịch của tôi là bao nhiêu?",
  "Tôi có bao nhiêu giao dịch liên quan đến mua sắm trực tuyến?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc ăn uống ngoài nhà?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc trả nợ?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc chuyển khoản cho người thân hoặc bạn bè?",
  "Tôi có bao nhiêu giao dịch liên quan đến các dịch vụ tiện ích?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc rút tiền mặt từ ATM?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc đầu tư?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc tiết kiệm?",
  "Tôi có nhận được thu nhập không thường xuyên từ công việc tự do không?",
  "Tôi có nhận được thu nhập từ tiền lãi đầu tư cổ phiếu không?",
  "Tôi có thu nhập từ việc cho thuê bất động sản không? Nếu có, số tiền đó là bao nhiêu?",
  "Tôi có nhận được các khoản hỗ trợ tài chính từ gia đình hoặc bạn bè không?",
  "Tôi có nhận được các khoản tiền thưởng từ công ty không? Nếu có, tổng số tiền là bao nhiêu trong năm qua?",
  "Thu nhập của tôi có thay đổi theo mùa không? Nếu có, thay đổi như thế nào?",
  "Tôi có nhận được tiền hoàn thuế không? Nếu có, số tiền đó là bao nhiêu?",
  "Tôi có nhận được các khoản tiền trợ cấp từ chính phủ không?",
  "Tôi có thu nhập từ việc bán hàng hóa hoặc dịch vụ tự sản xuất không?",
  "Tôi có nhận được các khoản tiền từ việc tham gia khảo sát hoặc nghiên cứu không?",
  "Tôi chi tiêu bao nhiêu tiền cho các dịch vụ đăng ký hàng tháng (như Netflix, Spotify)?",
  "Tôi chi tiêu bao nhiêu tiền cho việc mua sắm đồ điện tử?",
  "Tôi chi tiêu bao nhiêu tiền cho việc sửa chữa và bảo dưỡng ô tô?",
  "Tôi chi tiêu bao nhiêu tiền cho việc mua sắm đồ nội thất?",
  "Tôi chi tiêu bao nhiêu tiền cho các hoạt động thể thao và thể dục?",
  "Tôi chi tiêu bao nhiêu tiền cho việc học thêm hoặc các khóa học kỹ năng?",
  "Tôi chi tiêu bao nhiêu tiền cho các hoạt động từ thiện và đóng góp?",
  "Tôi chi tiêu bao nhiêu tiền cho các chuyến đi công tác?",
  "Tôi chi tiêu bao nhiêu tiền cho việc mua sắm vật nuôi và chăm sóc vật nuôi?",
  "Tôi chi tiêu bao nhiêu tiền cho việc tổ chức tiệc và các sự kiện gia đình?",
  "Tôi có quỹ tiết kiệm cho việc mua nhà không? Nếu có, số tiền hiện tại là bao nhiêu?",
  "Tôi có quỹ tiết kiệm cho việc mua ô tô không? Nếu có, số tiền hiện tại là bao nhiêu?",
  "Tôi có quỹ tiết kiệm cho việc du lịch không? Nếu có, số tiền hiện tại là bao nhiêu?",
  "Tôi có quỹ tiết kiệm cho việc học hành của con cái không? Nếu có, số tiền hiện tại là bao nhiêu?",
  "Tôi có quỹ tiết kiệm cho việc chăm sóc sức khỏe không? Nếu có, số tiền hiện tại là bao nhiêu?",
  "Tôi có quỹ tiết kiệm cho các tình huống khẩn cấp không? Nếu có, số tiền hiện tại là bao nhiêu?",
  "Tôi có quỹ tiết kiệm cho việc nghỉ hưu không? Nếu có, số tiền hiện tại là bao nhiêu?",
  "Tôi có kế hoạch tiết kiệm để mua bất động sản không? Nếu có, số tiền cần tiết kiệm là bao nhiêu?",
  "Tôi có quỹ tiết kiệm cho việc khởi nghiệp không? Nếu có, số tiền hiện tại là bao nhiêu?",
  "Tôi có kế hoạch tiết kiệm để đạt được mục tiêu tài chính dài hạn nào khác không? Nếu có, mục tiêu đó là gì?",
  "Tôi có bao nhiêu khoản vay cá nhân khác nhau?",
  "Tôi có bao nhiêu khoản vay mua xe hơi?",
  "Tôi có bao nhiêu khoản vay mua nhà?",
  "Tôi có khoản vay nào đang được hưởng lãi suất ưu đãi không?",
  "Tôi có khoản vay nào đang bị áp dụng lãi suất cao không?",
  "Tôi có khoản vay nào đang được tái cấu trúc không?",
  "Tôi có kế hoạch trả hết nợ trong bao lâu?",
  "Tôi có khoản nợ nào đang bị nợ xấu không? Nếu có, khoản nợ đó là gì?",
  "Tôi có kế hoạch giảm nợ như thế nào?",
  "Tôi có sử dụng dịch vụ tư vấn tài chính để quản lý nợ không?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc thanh toán hóa đơn?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc thanh toán tiền thuê nhà hoặc tiền vay?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc mua sắm tại siêu thị?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc thanh toán học phí?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc thanh toán tiền điện thoại?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc thanh toán tiền internet?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc mua sắm thiết bị công nghệ?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc thanh toán tiền bảo hiểm?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc chuyển tiền quốc tế?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc trả tiền dịch vụ tư vấn?",
  "Về Quản Lý Tài Chính Cá Nhân",
  "Tôi có lập ngân sách hàng tháng không? Nếu có, ngân sách đó như thế nào?",
  "Tôi có theo dõi các khoản thu chi hàng tháng không? Nếu có, bằng cách nào?",
  "Tôi có sử dụng ứng dụng quản lý tài chính nào không? Nếu có, ứng dụng đó là gì?",
  "Tôi có lập kế hoạch tài chính cho các sự kiện lớn trong đời không? Nếu có, đó là gì?",
  "Tôi có lập kế hoạch tài chính cho việc nghỉ hưu không?",
  "Tôi có lập kế hoạch tài chính cho việc mua sắm lớn không? Nếu có, đó là gì?",
  "Tôi có theo dõi tình hình tài chính cá nhân hàng tháng không? Nếu có, bằng cách nào?",
  "Tôi có tư vấn tài chính cá nhân không? Nếu có, tôi tìm kiếm tư vấn từ đâu?",
  "Tôi có lập kế hoạch tài chính dài hạn không? Nếu có, mục tiêu đó là gì?",
  "Tôi có lập kế hoạch tài chính cho gia đình không? Nếu có, kế hoạch đó như thế nào?",
  "Tổng số tiền thu nhập hàng tháng của tôi thay đổi như thế nào trong năm qua?",
  "Chi tiêu hàng tháng của tôi thay đổi ra sao trong năm qua?",
  "Mức tiết kiệm hàng tháng của tôi tăng hay giảm trong năm qua?",
  "Tỷ lệ giữa thu nhập và chi tiêu hàng tháng của tôi là bao nhiêu?",
  "Số tiền tôi chi tiêu cho từng loại chi phí (ăn uống, giải trí, giáo dục, v.v.) thay đổi như thế nào theo tháng?",
  "Số giao dịch hàng tháng của tôi có xu hướng tăng hay giảm?",
  "Số tiền tôi tiết kiệm được hàng tháng so với mục tiêu đặt ra là bao nhiêu?",
  "Tổng số tiền nợ của tôi thay đổi như thế nào trong năm qua?",
  "Số tiền chi tiêu của tôi vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) thay đổi như thế nào?",
  "Tỷ lệ tiết kiệm so với thu nhập hàng tháng của tôi là bao nhiêu?",
  "Trung bình số tiền thu nhập hàng tháng của tôi là bao nhiêu?",
  "Trung bình số tiền chi tiêu hàng tháng của tôi là bao nhiêu?",
  "Trung bình số tiền tiết kiệm hàng tháng của tôi là bao nhiêu?",
  "Số tiền chi tiêu hàng tháng của tôi cao nhất và thấp nhất trong năm qua là bao nhiêu?",
  "Số tiền thu nhập hàng tháng của tôi cao nhất và thấp nhất trong năm qua là bao nhiêu?",
  "Số tiền tiết kiệm hàng tháng của tôi cao nhất và thấp nhất trong năm qua là bao nhiêu?",
  "Tỷ lệ chi tiêu vào các loại chi phí (ăn uống, giải trí, giáo dục, v.v.) của tôi là bao nhiêu?",
  "Tỷ lệ thu nhập từ các nguồn khác nhau (lương, đầu tư, kinh doanh, v.v.) của tôi là bao nhiêu?",
  "Tỷ lệ chi tiêu vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) của tôi là bao nhiêu?",
  "Số giao dịch hàng tháng của tôi trung bình là bao nhiêu?",
  "Quản Lý Giao Dịch",
  "Tôi có bao nhiêu giao dịch trong tháng này?",
  "Số tiền trung bình của mỗi giao dịch là bao nhiêu?",
  "Giao dịch nào là lớn nhất trong tháng này?",
  "Giao dịch nào là nhỏ nhất trong tháng này?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc mua sắm trực tuyến?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc thanh toán hóa đơn?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc rút tiền mặt từ ATM?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc chuyển tiền cho người thân hoặc bạn bè?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc trả nợ?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc đầu tư?",
  "Số tiền tôi tiết kiệm được mỗi tháng là bao nhiêu?",
  "Số tiền tôi đầu tư mỗi tháng là bao nhiêu?",
  "Số tiền tôi chi tiêu cho các hoạt động từ thiện mỗi tháng là bao nhiêu?",
  "Số tiền tôi dành cho việc giải trí và du lịch mỗi tháng là bao nhiêu?",
  "Số tiền tôi chi tiêu cho việc mua sắm hàng tháng là bao nhiêu?",
  "Số tiền tôi chi tiêu cho các dịch vụ tiện ích hàng tháng là bao nhiêu?",
  "Số tiền tôi chi tiêu cho việc chăm sóc sức khỏe hàng tháng là bao nhiêu?",
  "Số tiền tôi chi tiêu cho việc giáo dục hàng tháng là bao nhiêu?",
  "Số tiền tôi chi tiêu cho việc thuê nhà hoặc trả góp nhà hàng tháng là bao nhiêu?",
  "Số tiền tôi chi tiêu cho việc bảo dưỡng và sửa chữa ô tô hàng tháng là bao nhiêu?",
  "Số tiền chi tiêu hàng tháng của tôi có xu hướng tăng hay giảm?",
  "Số tiền thu nhập hàng tháng của tôi có xu hướng tăng hay giảm?",
  "Tỷ lệ tiết kiệm hàng tháng của tôi có đạt được mục tiêu không?",
  "Số tiền chi tiêu hàng tháng của tôi có vượt quá thu nhập không?",
  "Tôi có bao nhiêu giao dịch không cần thiết hàng tháng?",
  "Số tiền tôi có thể tiết kiệm thêm bằng cách giảm chi tiêu không cần thiết là bao nhiêu?",
  "Tôi có bao nhiêu giao dịch liên quan đến việc trả lãi suất nợ?",
  "Số tiền tôi chi tiêu cho việc trả lãi suất nợ hàng tháng là bao nhiêu?",
  "Tỷ lệ thu nhập từ các nguồn không chính thống của tôi là bao nhiêu?",
  "Số tiền tôi dành cho việc đầu tư vào các tài sản dài hạn là bao nhiêu?",
  "Vẽ biểu đồ để thấy tổng thu nhập hàng tháng của tôi thay đổi như thế nào trong năm qua.",
  "Vẽ biểu đồ để thấy chi tiêu hàng tháng của tôi thay đổi ra sao trong năm qua.",
  "Vẽ biểu đồ để thấy mức tiết kiệm hàng tháng của tôi tăng hay giảm trong năm qua.",
  "Vẽ biểu đồ để thấy tỷ lệ giữa thu nhập và chi tiêu hàng tháng của tôi.",
  "Vẽ biểu đồ để thấy số tiền tôi chi tiêu cho từng loại chi phí (ăn uống, giải trí, giáo dục, v.v.) thay đổi như thế nào theo tháng.",
  "Vẽ biểu đồ để thấy số giao dịch hàng tháng của tôi có xu hướng tăng hay giảm.",
  "Vẽ biểu đồ để thấy số tiền tôi tiết kiệm được hàng tháng so với mục tiêu đặt ra.",
  "Vẽ biểu đồ để thấy tổng số tiền nợ của tôi thay đổi như thế nào trong năm qua.",
  "Vẽ biểu đồ để thấy số tiền tôi chi tiêu vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) thay đổi như thế nào.",
  "Vẽ biểu đồ để thấy tỷ lệ tiết kiệm so với thu nhập hàng tháng của tôi.",
  "Vẽ biểu đồ để thấy trung bình số tiền thu nhập hàng tháng của tôi là bao nhiêu.",
  "Vẽ biểu đồ để thấy trung bình số tiền chi tiêu hàng tháng của tôi là bao nhiêu.",
  "Vẽ biểu đồ để thấy trung bình số tiền tiết kiệm hàng tháng của tôi là bao nhiêu.",
  "Vẽ biểu đồ để thấy số tiền chi tiêu hàng tháng cao nhất và thấp nhất của tôi trong năm qua.",
  "Vẽ biểu đồ để thấy số tiền thu nhập hàng tháng cao nhất và thấp nhất của tôi trong năm qua.",
  "Vẽ biểu đồ để thấy số tiền tiết kiệm hàng tháng cao nhất và thấp nhất của tôi trong năm qua.",
  "Vẽ biểu đồ để thấy tỷ lệ chi tiêu vào các loại chi phí (ăn uống, giải trí, giáo dục, v.v.) của tôi.",
  "Vẽ biểu đồ để thấy tỷ lệ thu nhập từ các nguồn khác nhau (lương, đầu tư, kinh doanh, v.v.) của tôi.",
  "Vẽ biểu đồ để thấy tỷ lệ chi tiêu vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) của tôi.",
  "Vẽ biểu đồ để thấy trung bình số giao dịch hàng tháng của tôi là bao nhiêu.",
  "Vẽ biểu đồ để thấy số lượng giao dịch trong tháng này của tôi.",
  "Vẽ biểu đồ để thấy số tiền trung bình của mỗi giao dịch.",
  "Vẽ biểu đồ để thấy giao dịch lớn nhất trong tháng này của tôi.",
  "Vẽ biểu đồ để thấy giao dịch nhỏ nhất trong tháng này của tôi.",
  "Vẽ biểu đồ để thấy số lượng giao dịch liên quan đến việc mua sắm trực tuyến của tôi.",
  "Vẽ biểu đồ để thấy số lượng giao dịch liên quan đến việc thanh toán hóa đơn của tôi.",
  "Vẽ biểu đồ để thấy số lượng giao dịch liên quan đến việc rút tiền mặt từ ATM của tôi.",
  "Vẽ biểu đồ để thấy số lượng giao dịch liên quan đến việc chuyển tiền cho người thân hoặc bạn bè của tôi.",
  "Vẽ biểu đồ để thấy số lượng giao dịch liên quan đến việc trả nợ của tôi.",
  "Vẽ biểu đồ để thấy số lượng giao dịch liên quan đến việc đầu tư của tôi.",
  "Quản Lý Tiền",
  "Vẽ biểu đồ để thấy số tiền tôi tiết kiệm được mỗi tháng.",
  "Vẽ biểu đồ để thấy số tiền tôi đầu tư mỗi tháng.",
  "Vẽ biểu đồ để thấy số tiền tôi chi tiêu cho các hoạt động từ thiện mỗi tháng.",
  "Vẽ biểu đồ để thấy số tiền tôi dành cho việc giải trí và du lịch mỗi tháng.",
  "Vẽ biểu đồ để thấy số tiền tôi chi tiêu cho việc mua sắm hàng tháng.",
  "Vẽ biểu đồ để thấy số tiền tôi chi tiêu cho các dịch vụ tiện ích hàng tháng.",
  "Vẽ biểu đồ để thấy số tiền tôi chi tiêu cho việc chăm sóc sức khỏe hàng tháng.",
  "Vẽ biểu đồ để thấy số tiền tôi chi tiêu cho việc giáo dục hàng tháng.",
  "Vẽ biểu đồ để thấy số tiền tôi chi tiêu cho việc thuê nhà hoặc trả góp nhà hàng tháng.",
  "Vẽ biểu đồ để thấy số tiền tôi chi tiêu cho việc bảo dưỡng và sửa chữa ô tô hàng tháng.",
  "Phân Tích Tài Chính",
  "Vẽ biểu đồ để thấy xu hướng thay đổi của số tiền chi tiêu hàng tháng của tôi.",
  "Vẽ biểu đồ để thấy xu hướng thay đổi của số tiền thu nhập hàng tháng của tôi.",
  "Vẽ biểu đồ để thấy tỷ lệ tiết kiệm hàng tháng của tôi có đạt được mục tiêu không.",
  "Vẽ biểu đồ để thấy số tiền chi tiêu hàng tháng của tôi có vượt quá thu nhập không.",
  "Vẽ biểu đồ để thấy số lượng giao dịch không cần thiết hàng tháng của tôi.",
  "Vẽ biểu đồ để thấy số tiền tôi có thể tiết kiệm thêm bằng cách giảm chi tiêu không cần thiết.",
  "Vẽ biểu đồ để thấy số lượng giao dịch liên quan đến việc trả lãi suất nợ của tôi.",
  "Vẽ biểu đồ để thấy số tiền tôi chi tiêu cho việc trả lãi suất nợ hàng tháng.",
  "Vẽ biểu đồ để thấy tỷ lệ thu nhập từ các nguồn không chính thống của tôi.",
  "Vẽ biểu đồ để thấy số tiền tôi dành cho việc đầu tư vào các tài sản dài hạn.",
  "Vẽ biểu đồ đường để thấy tổng thu nhập hàng tháng của tôi thay đổi như thế nào trong năm qua.",
  "Vẽ biểu đồ đường để thấy chi tiêu hàng tháng của tôi thay đổi ra sao trong năm qua.",
  "Vẽ biểu đồ đường để thấy mức tiết kiệm hàng tháng của tôi tăng hay giảm trong năm qua.",
  "Vẽ biểu đồ đường để thấy tỷ lệ giữa thu nhập và chi tiêu hàng tháng của tôi.",
  "Vẽ biểu đồ cột để thấy số tiền tôi chi tiêu cho từng loại chi phí (ăn uống, giải trí, giáo dục, v.v.) thay đổi như thế nào theo tháng.",
  "Vẽ biểu đồ đường để thấy số giao dịch hàng tháng của tôi có xu hướng tăng hay giảm.",
  "Vẽ biểu đồ đường để thấy số tiền tôi tiết kiệm được hàng tháng so với mục tiêu đặt ra.",
  "Vẽ biểu đồ đường để thấy tổng số tiền nợ của tôi thay đổi như thế nào trong năm qua.",
  "Vẽ biểu đồ cột để thấy số tiền tôi chi tiêu vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) thay đổi như thế nào.",
  "Vẽ biểu đồ đường để thấy tỷ lệ tiết kiệm so với thu nhập hàng tháng của tôi.",
  "Vẽ biểu đồ cột để thấy số tiền thu nhập hàng tháng cao nhất và thấp nhất của tôi trong năm qua.",
  "Vẽ biểu đồ cột để thấy số tiền tiết kiệm hàng tháng cao nhất và thấp nhất của tôi trong năm qua.",
  "Vẽ biểu đồ tròn để thấy tỷ lệ chi tiêu vào các loại chi phí (ăn uống, giải trí, giáo dục, v.v.) của tôi.",
  "Vẽ biểu đồ tròn để thấy tỷ lệ thu nhập từ các nguồn khác nhau (lương, đầu tư, kinh doanh, v.v.) của tôi.",
  "Vẽ biểu đồ tròn để thấy tỷ lệ chi tiêu vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) của tôi.",
  "Vẽ biểu đồ cột để thấy trung bình số giao dịch hàng tháng của tôi là bao nhiêu.",
  "Vẽ biểu đồ khác phù hợp với số liệu trên",
  "Thống kê tổng thu nhập hàng tháng của tôi trong năm qua.",
  "Thống kê tổng chi tiêu hàng tháng của tôi trong năm qua.",
  "Thống kê mức tiết kiệm hàng tháng của tôi trong năm qua.",
  "Thống kê tỷ lệ giữa thu nhập và chi tiêu hàng tháng của tôi.",
  "Thống kê số tiền tôi chi tiêu cho từng loại chi phí (ăn uống, giải trí, giáo dục, v.v.) trong năm qua.",
  "Thống kê số giao dịch hàng tháng của tôi trong năm qua.",
  "Thống kê số tiền tôi tiết kiệm được hàng tháng so với mục tiêu đặt ra.",
  "Thống kê tổng số tiền nợ của tôi trong năm qua.",
  "Thống kê số tiền tôi chi tiêu vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) trong năm qua.",
  "Thống kê tỷ lệ tiết kiệm so với thu nhập hàng tháng của tôi.",
  "Thống kê trung bình số tiền thu nhập hàng tháng của tôi.",
  "Thống kê trung bình số tiền chi tiêu hàng tháng của tôi.",
  "Thống kê trung bình số tiền tiết kiệm hàng tháng của tôi.",
  "Thống kê số tiền chi tiêu hàng tháng cao nhất và thấp nhất trong năm qua.",
  "Thống kê số tiền thu nhập hàng tháng cao nhất và thấp nhất trong năm qua.",
  "Thống kê số tiền tiết kiệm hàng tháng cao nhất và thấp nhất trong năm qua.",
  "Thống kê tỷ lệ chi tiêu vào các loại chi phí (ăn uống, giải trí, giáo dục, v.v.) của tôi.",
  "Thống kê tỷ lệ thu nhập từ các nguồn khác nhau (lương, đầu tư, kinh doanh, v.v.) của tôi.",
  "Thống kê tỷ lệ chi tiêu vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) của tôi.",
  "Thống kê số giao dịch hàng tháng của tôi trung bình trong năm qua.",
  "Phân tích xu hướng thay đổi tổng thu nhập hàng tháng của tôi trong năm qua.",
  "Phân tích xu hướng thay đổi chi tiêu hàng tháng của tôi trong năm qua.",
  "Phân tích mức tiết kiệm hàng tháng của tôi trong năm qua để xem có tăng hoặc giảm không.",
  "Phân tích tỷ lệ giữa thu nhập và chi tiêu hàng tháng của tôi.",
  "Phân tích số tiền tôi chi tiêu cho từng loại chi phí (ăn uống, giải trí, giáo dục, v.v.) để xác định loại chi phí cao nhất.",
  "Phân tích số giao dịch hàng tháng của tôi để thấy có xu hướng tăng hay giảm.",
  "Phân tích số tiền tôi tiết kiệm được hàng tháng so với mục tiêu đặt ra.",
  "Phân tích tổng số tiền nợ của tôi trong năm qua để thấy sự thay đổi.",
  "Phân tích số tiền tôi chi tiêu vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) để xem mục tiêu nào tốn nhiều nhất.",
  "Phân tích tỷ lệ tiết kiệm so với thu nhập hàng tháng của tôi để xác định khả năng tiết kiệm.",
  "Phân tích trung bình số tiền thu nhập hàng tháng của tôi để so sánh với các tháng khác.",
  "Phân tích trung bình số tiền chi tiêu hàng tháng của tôi để xác định sự phân bổ chi tiêu.",
  "Phân tích trung bình số tiền tiết kiệm hàng tháng của tôi để xem có đạt được mục tiêu không.",
  "Phân tích số tiền chi tiêu hàng tháng cao nhất và thấp nhất trong năm qua để xác định biến động lớn nhất.",
  "Phân tích số tiền thu nhập hàng tháng cao nhất và thấp nhất trong năm qua để hiểu mức biến động.",
  "Phân tích số tiền tiết kiệm hàng tháng cao nhất và thấp nhất trong năm qua để đánh giá khả năng tiết kiệm.",
  "Phân tích tỷ lệ chi tiêu vào các loại chi phí (ăn uống, giải trí, giáo dục, v.v.) để tối ưu hóa chi tiêu.",
  "Phân tích tỷ lệ thu nhập từ các nguồn khác nhau (lương, đầu tư, kinh doanh, v.v.) để xem nguồn thu nhập nào chính.",
  "Phân tích tỷ lệ chi tiêu vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) để tối ưu hóa ngân sách.",
  "Phân tích số lượng giao dịch hàng tháng của tôi để xác định tần suất giao dịch.",
  "Phân tích số lượng giao dịch không cần thiết hàng tháng để xác định các khoản chi không cần thiết.",
  "Phân tích số tiền chi tiêu cho các hoạt động từ thiện hàng tháng để xem có thể tăng cường không.",
  "Phân tích số tiền đầu tư mỗi tháng để đánh giá chiến lược đầu tư của tôi.",
  "Phân tích số tiền chi tiêu cho giải trí và du lịch hàng tháng để xem có thể giảm bớt không.",
  "Phân tích số tiền chi tiêu cho việc mua sắm hàng tháng để đánh giá nhu cầu tiêu dùng.",
  "Phân tích số tiền chi tiêu cho các dịch vụ tiện ích hàng tháng để tìm cách tiết kiệm.",
  "Phân tích số tiền chi tiêu cho chăm sóc sức khỏe hàng tháng để kiểm tra sự cần thiết của các chi phí này.",
  "Phân tích số tiền chi tiêu cho giáo dục hàng tháng để đánh giá hiệu quả đầu tư vào học tập.",
  "Phân tích số tiền chi tiêu cho thuê nhà hoặc trả góp nhà hàng tháng để xác định ảnh hưởng đến ngân sách.",
  "Phân tích số tiền chi tiêu cho bảo dưỡng và sửa chữa ô tô hàng tháng để thấy sự cần thiết của các khoản chi này.",
  "Đề xuất cách tối ưu hóa tổng thu nhập hàng tháng của tôi.",
  "Đề xuất phương pháp giảm chi tiêu hàng tháng của tôi.",
  "Đề xuất cách tăng mức tiết kiệm hàng tháng của tôi.",
  "Đề xuất cách cải thiện tỷ lệ giữa thu nhập và chi tiêu hàng tháng của tôi.",
  "Đề xuất cách giảm chi tiêu cho từng loại chi phí (ăn uống, giải trí, giáo dục, v.v.).",
  "Đề xuất phương pháp tăng cường số lượng giao dịch hàng tháng của tôi nếu cần.",
  "Đề xuất cách tăng số tiền tôi tiết kiệm được hàng tháng để đạt mục tiêu.",
  "Đề xuất cách giảm tổng số tiền nợ của tôi hiệu quả hơn.",
  "Đề xuất cách phân bổ số tiền chi tiêu vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) hợp lý hơn.",
  "Đề xuất cách cải thiện tỷ lệ tiết kiệm so với thu nhập hàng tháng của tôi.",
  "Đề xuất cách tối ưu hóa thu nhập hàng tháng của tôi để đạt được sự ổn định tài chính.",
  "Đề xuất phương pháp giảm chi tiêu hàng tháng để phù hợp với ngân sách.",
  "Đề xuất cách tăng cường mức tiết kiệm hàng tháng dựa trên thu nhập hiện tại.",
  "Đề xuất cách điều chỉnh chi tiêu hàng tháng cao nhất và thấp nhất để phù hợp hơn.",
  "Đề xuất cách tăng cường thu nhập hàng tháng cao nhất và cải thiện thu nhập thấp nhất.",
  "Đề xuất cách tối ưu hóa số tiền tiết kiệm hàng tháng cao nhất và thấp nhất.",
  "Đề xuất cách phân bổ chi tiêu vào các loại chi phí (ăn uống, giải trí, giáo dục, v.v.) hợp lý hơn.",
  "Đề xuất cách tối ưu hóa tỷ lệ thu nhập từ các nguồn khác nhau (lương, đầu tư, kinh doanh, v.v.).",
  "Đề xuất cách phân bổ chi tiêu vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) hiệu quả hơn.",
  "Đề xuất cách tăng cường số lượng giao dịch hàng tháng nếu cần thiết.",
  "Đề xuất cách giảm số lượng giao dịch không cần thiết hàng tháng.",
  "Đề xuất cách tăng cường số tiền chi tiêu cho các hoạt động từ thiện hàng tháng.",
  "Đề xuất cách tối ưu hóa số tiền đầu tư mỗi tháng để đạt được lợi nhuận tốt nhất.",
  "Đề xuất cách giảm số tiền chi tiêu cho giải trí và du lịch hàng tháng.",
  "Đề xuất cách tối ưu hóa chi tiêu cho việc mua sắm hàng tháng.",
  "Đề xuất cách giảm số tiền chi tiêu cho các dịch vụ tiện ích hàng tháng.",
  "Đề xuất cách điều chỉnh số tiền chi tiêu cho chăm sóc sức khỏe hàng tháng.",
  "Đề xuất cách tối ưu hóa số tiền chi tiêu cho giáo dục hàng tháng.",
  "Đề xuất cách giảm chi tiêu cho thuê nhà hoặc trả góp nhà hàng tháng.",
  "Đề xuất cách tối ưu hóa số tiền chi tiêu cho bảo dưỡng và sửa chữa ô tô hàng tháng.",
  "Gợi ý cách tối ưu hóa tổng thu nhập hàng tháng của tôi.",
  "Gợi ý phương pháp giảm chi tiêu hàng tháng của tôi.",
  "Gợi ý cách tăng mức tiết kiệm hàng tháng của tôi.",
  "Gợi ý cách cải thiện tỷ lệ giữa thu nhập và chi tiêu hàng tháng của tôi.",
  "Gợi ý cách giảm chi tiêu cho từng loại chi phí (ăn uống, giải trí, giáo dục, v.v.).",
  "Gợi ý phương pháp tăng cường số lượng giao dịch hàng tháng của tôi nếu cần.",
  "Gợi ý cách tăng số tiền tôi tiết kiệm được hàng tháng để đạt mục tiêu.",
  "Gợi ý cách giảm tổng số tiền nợ của tôi hiệu quả hơn.",
  "Gợi ý cách phân bổ số tiền chi tiêu vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) hợp lý hơn.",
  "Gợi ý cách cải thiện tỷ lệ tiết kiệm so với thu nhập hàng tháng của tôi.",
  "Gợi ý cách tối ưu hóa thu nhập hàng tháng của tôi để đạt được sự ổn định tài chính.",
  "Gợi ý phương pháp giảm chi tiêu hàng tháng để phù hợp với ngân sách.",
  "Gợi ý cách tăng cường mức tiết kiệm hàng tháng dựa trên thu nhập hiện tại.",
  "Gợi ý cách điều chỉnh chi tiêu hàng tháng cao nhất và thấp nhất để phù hợp hơn.",
  "Gợi ý cách tăng cường thu nhập hàng tháng cao nhất và cải thiện thu nhập thấp nhất.",
  "Gợi ý cách tối ưu hóa số tiền tiết kiệm hàng tháng cao nhất và thấp nhất.",
  "Gợi ý cách phân bổ chi tiêu vào các loại chi phí (ăn uống, giải trí, giáo dục, v.v.) hợp lý hơn.",
  "Gợi ý cách tối ưu hóa tỷ lệ thu nhập từ các nguồn khác nhau (lương, đầu tư, kinh doanh, v.v.).",
  "Gợi ý cách phân bổ chi tiêu vào các mục tiêu cụ thể (mua nhà, mua xe, du lịch) hiệu quả hơn.",
  "Gợi ý cách tăng cường số lượng giao dịch hàng tháng nếu cần thiết.",
  "Gợi ý cách giảm số lượng giao dịch không cần thiết hàng tháng.",
  "Gợi ý cách tăng cường số tiền chi tiêu cho các hoạt động từ thiện hàng tháng.",
  "Gợi ý cách tối ưu hóa số tiền đầu tư mỗi tháng để đạt được lợi nhuận tốt nhất.",
  "Gợi ý cách giảm số tiền chi tiêu cho giải trí và du lịch hàng tháng.",
  "Gợi ý cách tối ưu hóa chi tiêu cho việc mua sắm hàng tháng.",
  "Gợi ý cách giảm số tiền chi tiêu cho các dịch vụ tiện ích hàng tháng.",
  "Gợi ý cách điều chỉnh số tiền chi tiêu cho chăm sóc sức khỏe hàng tháng.",
  "Gợi ý cách tối ưu hóa số tiền chi tiêu cho giáo dục hàng tháng.",
  "Gợi ý cách giảm chi tiêu cho thuê nhà hoặc trả góp nhà hàng tháng.",
  "Tuần trước tôi đã chi tiêu bao nhiêu cho các loại chi phí khác nhau?",
  "Tuần trước tổng thu nhập của tôi là bao nhiêu?",
  "Tuần trước tôi đã tiết kiệm được bao nhiêu tiền?",
  "Tuần trước số tiền nợ của tôi là bao nhiêu?",
  "Tuần trước tôi đã chi tiêu nhiều nhất vào mục nào?",
  "Tuần trước tôi đã chi tiêu ít nhất vào mục nào?",
  "Tuần trước tỷ lệ giữa thu nhập và chi tiêu của tôi là bao nhiêu?",
  "Tuần trước số tiền tôi đầu tư là bao nhiêu?",
  "Tuần trước tôi đã chi bao nhiêu cho giải trí và du lịch?",
  "Tuần trước tôi đã chi bao nhiêu cho các dịch vụ tiện ích?",
  "Tuần trước tôi đã chi bao nhiêu cho chăm sóc sức khỏe?",
  "Tuần trước tôi đã chi bao nhiêu cho việc mua sắm?",
  "Tuần trước tôi đã chi bao nhiêu cho việc giáo dục?",
  "Tuần trước tôi đã chi bao nhiêu cho bảo dưỡng và sửa chữa ô tô?",
  "Tuần trước có bao nhiêu giao dịch không cần thiết được thực hiện?",
  "Tuần trước số tiền tôi chi cho các hoạt động từ thiện là bao nhiêu?",
  "Tuần trước số tiền tôi chi tiêu cho thuê nhà hoặc trả góp là bao nhiêu?",
  "Tuần trước số tiền tôi chi tiêu cho chăm sóc thú cưng là bao nhiêu?",
  "Tuần trước tôi đã chi bao nhiêu cho các khoản vay và trả góp?",
  "Tuần trước số tiền tôi chi tiêu cho việc chuyển tiền cho người thân hoặc bạn bè là bao",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho các loại chi phí khác nhau?",
  "Hôm qua tôi đã tiết kiệm được bao nhiêu tiền?",
  "Hôm qua tổng thu nhập của tôi là bao nhiêu?",
  "Hôm qua có bao nhiêu giao dịch được thực hiện?",
  "Hôm qua tôi đã chi tiêu nhiều nhất vào mục nào?",
  "Hôm qua tôi đã chi tiêu ít nhất vào mục nào?",
  "Hôm qua tỷ lệ giữa thu nhập và chi tiêu của tôi là bao nhiêu?",
  "Hôm qua số tiền nợ của tôi là bao nhiêu?",
  "Hôm qua số tiền tôi đầu tư là bao nhiêu?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho giải trí và du lịch?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho các dịch vụ tiện ích?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho chăm sóc sức khỏe?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho việc mua sắm?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho việc giáo dục?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho bảo dưỡng và sửa chữa ô tô?",
  "Hôm qua có bao nhiêu giao dịch không cần thiết được thực hiện?",
  "Hôm qua số tiền tôi chi cho các hoạt động từ thiện là bao nhiêu?",
  "Hôm qua số tiền tôi chi tiêu cho thuê nhà hoặc trả góp là bao nhiêu?",
  "Hôm qua số tiền tôi chi tiêu cho chăm sóc thú cưng là bao nhiêu?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho các khoản vay và trả góp?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho việc chuyển tiền cho người thân hoặc bạn bè?",
  "Hôm qua số tiền tôi chi tiêu cho các món quà là bao nhiêu?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho các sự kiện đặc biệt (tiệc, sinh nhật, v.v.)?",
  "Hôm qua tổng số tiền thu nhập từ các nguồn khác nhau là bao nhiêu?",
  "Hôm qua tôi đã chi bao nhiêu cho việc thanh toán hóa đơn?",
  "Hôm qua số tiền tôi chi tiêu cho việc bảo trì thiết bị gia đình là bao nhiêu?",
  "Hôm qua số tiền tôi chi tiêu cho việc rút tiền mặt từ ATM là bao nhiêu?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho các khoản chi tiêu bất thường?",
  "Hôm qua tổng số giao dịch thẻ tín dụng của tôi là bao nhiêu?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho việc bảo hiểm?",
  "Làm thế nào để lập kế hoạch tài chính cá nhân?",
  "Các bước cơ bản để lập kế hoạch tài chính cá nhân là gì?",
  "Làm thế nào để xác định và ưu tiên các mục tiêu tài chính của mình?",
  "Quản lý ngân sách cá nhân như thế nào?",
  "Làm thế nào để theo dõi thu nhập và chi tiêu hàng tháng?",
  "Có công cụ hoặc ứng dụng nào giúp quản lý ngân sách hiệu quả?",
  "Làm thế nào để tiết kiệm tiền?",
  "Có những chiến lược nào để tiết kiệm tiền một cách hiệu quả?",
  "Làm sao để tạo ra một quỹ khẩn cấp?",
  "Đầu tư như thế nào cho an toàn và hiệu quả?",
  "Những kênh đầu tư nào phù hợp với người mới bắt đầu?",
  "Làm sao để phân tích và lựa chọn cổ phiếu hoặc quỹ đầu tư?",
  "Làm thế nào để quản lý nợ hiệu quả?",
  "Cách nào tốt nhất để trả nợ tín dụng hoặc các khoản vay khác?",
  "Làm thế nào để tránh nợ xấu?",
  "Làm thế nào để cải thiện điểm tín dụng (credit score)?",
  "Những yếu tố nào ảnh hưởng đến điểm tín dụng?",
  "Làm sao để cải thiện điểm tín dụng trong thời gian ngắn?",
  "Làm thế nào để lập kế hoạch nghỉ hưu?",
  "Cần bắt đầu lập kế hoạch nghỉ hưu từ khi nào?",
  "Những lựa chọn đầu tư nào phù hợp cho quỹ hưu trí?",
  "Bảo hiểm cá nhân cần lưu ý những gì?",
  "Những loại bảo hiểm cá nhân nào là cần thiết?",
  "Làm sao để chọn gói bảo hiểm phù hợp với nhu cầu cá nhân?",
  "Làm thế nào để tối ưu hóa thuế cá nhân?",
  "Có những khoản giảm trừ thuế nào mà tôi có thể tận dụng?",
  "Làm sao để lập kế hoạch thuế hiệu quả?",
  "Làm thế nào để giáo dục tài chính cho trẻ em?",
  "Khi nào nên bắt đầu giáo dục tài chính cho trẻ em?",
  "Có những phương pháp nào giúp trẻ hiểu về quản lý tiền bạc?",
  "Kế Hoạch Tài Chính Cá Nhân",
  "Làm thế nào để lập kế hoạch tài chính cá nhân?",
  "Các bước cơ bản để lập kế hoạch tài chính cá nhân là gì?",
  "Làm thế nào để xác định mục tiêu tài chính cá nhân?",
  "Làm thế nào để ưu tiên các mục tiêu tài chính?",
  "Làm thế nào để theo dõi tiến độ đạt được mục tiêu tài chính?",
  "Khi nào nên xem xét lại kế hoạch tài chính cá nhân?",
  "Có công cụ hoặc ứng dụng nào giúp lập kế hoạch tài chính hiệu quả?",
  "Làm thế nào để dự báo chi tiêu và thu nhập trong tương lai?",
  "Làm thế nào để đánh giá tình hình tài chính hiện tại của mình?",
  "Những yếu tố nào cần xem xét khi lập kế hoạch tài chính dài hạn?",
  "Quản Lý Ngân Sách",
  "Làm thế nào để lập ngân sách cá nhân?",
  "Làm thế nào để theo dõi thu nhập hàng tháng?",
  "Làm thế nào để theo dõi chi tiêu hàng tháng?",
  "Có những công cụ hoặc ứng dụng nào giúp quản lý ngân sách hiệu quả?",
  "Làm thế nào để cắt giảm chi phí hàng tháng?",
  "Làm thế nào để duy trì ngân sách cá nhân?",
  "Làm thế nào để điều chỉnh ngân sách khi thu nhập thay đổi?",
  "Những chi phí nào cần được ưu tiên trong ngân sách?",
  "Làm thế nào để lập ngân sách cho các sự kiện bất ngờ?",
  "Làm thế nào để lập ngân sách cho kỳ nghỉ?",
  "Tiết Kiệm Tiền",
  "Làm thế nào để tiết kiệm tiền một cách hiệu quả?",
  "Làm sao để tạo ra một quỹ khẩn cấp?",
  "Có những chiến lược nào để tiết kiệm tiền hàng tháng?",
  "Làm thế nào để tiết kiệm tiền cho mục tiêu dài hạn?",
  "Làm thế nào để tiết kiệm tiền cho mua nhà?",
  "Làm thế nào để tiết kiệm tiền cho hưu trí?",
  "Có những cách nào để tiết kiệm tiền khi đi mua sắm?",
  "Làm sao để tiết kiệm tiền khi đi du lịch?",
  "Làm thế nào để tiết kiệm tiền khi ăn uống ngoài nhà?",
  "Làm thế nào để tiết kiệm tiền khi mua sắm trực tuyến?",
  "Đầu Tư",
  "Làm thế nào để bắt đầu đầu tư?",
  "Những kênh đầu tư nào phù hợp với người mới bắt đầu?",
  "Làm thế nào để phân tích cổ phiếu?",
  "Làm thế nào để chọn quỹ đầu tư phù hợp?",
  "Những yếu tố nào cần xem xét khi đầu tư vào bất động sản?",
  "Làm thế nào để đầu tư vào tiền điện tử?",
  "Làm thế nào để đa dạng hóa danh mục đầu tư?",
  "Làm thế nào để đánh giá rủi ro trong đầu tư?",
  "Khi nào nên bán cổ phiếu?",
  "Làm thế nào để đầu tư vào trái phiếu?",
  "Quản Lý Nợ",
  "Làm thế nào để quản lý nợ hiệu quả?",
  "Cách nào tốt nhất để trả nợ tín dụng?",
  "Làm thế nào để trả nợ vay sinh viên?",
  "Làm thế nào để trả nợ vay mua nhà?",
  "Làm sao để tránh nợ xấu?",
  "Khi nào nên vay tiền?",
  "Làm thế nào để giảm lãi suất vay?",
  "Làm thế nào để đàm phán lại điều khoản vay?",
  "Làm thế nào để quản lý nợ khi thu nhập giảm?",
  "Làm thế nào để tránh tình trạng nợ chồng chất?",
  "Điểm Tín Dụng",
  "Làm thế nào để cải thiện điểm tín dụng?",
  "Những yếu tố nào ảnh hưởng đến điểm tín dụng?",
  "Làm sao để kiểm tra điểm tín dụng?",
  "Làm thế nào để tăng điểm tín dụng trong thời gian ngắn?",
  "Những sai lầm phổ biến làm giảm điểm tín dụng là gì?",
  "Làm thế nào để xây dựng điểm tín dụng từ đầu?",
  "Làm thế nào để duy trì điểm tín dụng tốt?",
  "Làm sao để bảo vệ thông tin tín dụng?",
  "Những quyền lợi của người tiêu dùng khi bị từ chối tín dụng là gì?",
  "Làm thế nào để tranh chấp thông tin tín dụng không chính xác?",
  "Lập Kế Hoạch Hưu Trí",
  "Làm thế nào để lập kế hoạch nghỉ hưu?",
  "Cần bắt đầu lập kế hoạch nghỉ hưu từ khi nào?",
  "Những lựa chọn đầu tư nào phù hợp cho quỹ hưu trí?",
  "Làm thế nào để ước tính chi phí hưu trí?",
  "Làm thế nào để tối đa hóa khoản tiết kiệm hưu trí?",
  "Khi nào nên bắt đầu rút tiền từ quỹ hưu trí?",
  "Làm thế nào để duy trì cuộc sống thoải mái sau khi nghỉ hưu?",
  "Làm thế nào để lập kế hoạch hưu trí khi không có lương hưu?",
  "Làm thế nào để quản lý tài sản khi nghỉ hưu?",
  "Làm thế nào để lập kế hoạch hưu trí cho doanh nhân?",
  "Bảo Hiểm",
  "Làm thế nào để chọn gói bảo hiểm phù hợp?",
  "Những loại bảo hiểm cá nhân nào là cần thiết?",
  "Làm thế nào để so sánh các gói bảo hiểm khác nhau?",
  "Những yếu tố nào cần xem xét khi mua bảo hiểm nhân thọ?",
  "Làm thế nào để chọn bảo hiểm y tế phù hợp?",
  "Làm thế nào để giảm chi phí bảo hiểm?",
  "Khi nào nên xem xét lại gói bảo hiểm của mình?",
  "Làm thế nào để yêu cầu bồi thường bảo hiểm?",
  "Những lỗi phổ biến khi mua bảo hiểm là gì?",
  "Làm thế nào để bảo vệ tài sản bằng bảo hiểm?",
  "Tối Ưu Hóa Thuế",
  "Làm thế nào để tối ưu hóa thuế cá nhân?",
  "Có những khoản giảm trừ thuế nào mà tôi có thể tận dụng?",
  "Làm thế nào để lập kế hoạch thuế hiệu quả?",
  "Làm thế nào để giảm thiểu thuế phải nộp?",
  "Khi nào nên tìm kiếm sự giúp đỡ từ chuyên gia thuế?",
  "Những lỗi phổ biến khi kê khai thuế là gì?",
  "Làm thế nào để chuẩn bị hồ sơ thuế một cách hiệu quả?",
  "Những lợi ích thuế nào dành cho người lao động tự do?",
  "Làm thế nào để tối ưu hóa thuế khi đầu tư?",
  "Làm thế nào để tối ưu hóa thuế khi mua bán bất động sản?",
  "Giáo Dục Tài Chính",
  "Khi nào nên bắt đầu giáo dục tài chính cho trẻ em?",
  "Có những phương pháp nào giúp trẻ hiểu về quản lý tiền bạc?",
  "Làm thế nào để giúp trẻ tiết kiệm tiền?",
  "Làm thế nào để dạy trẻ về giá trị của tiền?",
  "Khi nào nên mở tài khoản tiết kiệm cho trẻ?",
  "Làm thế nào để dạy trẻ về đầu tư?",
  "Làm thế nào để dạy trẻ về quản lý nợ?",
  "Những sai lầm phổ biến khi giáo dục tài chính cho trẻ là gì?",
  "Làm thế nào để khuyến khích trẻ lập ngân sách?",
  "Làm thế nào để giáo dục tài chính thông qua các hoạt động hàng ngày?",
  "Chiến Lược Tài Chính Cá Nhân",
  "Làm thế nào để xây dựng chiến lược tài chính cá nhân?",
  "Những yếu tố nào cần xem xét khi xây dựng chiến lược tài chính?",
  "Làm thế nào để điều chỉnh chiến lược tài chính khi tình hình thay đổi?",
  "Làm thế nào để đảm bảo chiến lược tài chính bền vững?",
  "Làm thế nào để đo lường hiệu quả của chiến lược tài chính?",
  "Khi nào nên tìm kiếm sự giúp đỡ từ chuyên gia tài chính?",
  "Làm thế nào để xây dựng chiến lược tài chính cho gia đình?",
  "Làm thế nào để quản lý tài chính khi có thêm thành viên trong gia đình?",
  "Làm thế nào để lập kế hoạch tài chính cho mục tiêu dài hạn?",
  "Làm thế nào để đảm bảo chiến lược tài chính linh hoạt?",
  "Tài Chính Gia Đình",
  "Làm thế nào để quản lý tài chính gia đình?",
  "Làm thế nào để lập ngân sách gia đình?",
  "Làm thế nào để tiết kiệm tiền cho gia đình?",
  "Làm thế nào để đầu tư cho tương lai của con cái?",
  "Làm thế nào để quản lý nợ của gia đình?",
  "Làm thế nào để bảo vệ tài chính của gia đình bằng bảo hiểm?",
  "Làm thế nào để lập kế hoạch tài chính cho kỳ nghỉ gia đình?",
  "Làm thế nào để quản lý chi phí học hành của con cái?",
  "Làm thế nào để chuẩn bị tài chính cho việc sinh con?",
  "Làm thế nào để lập kế hoạch tài chính khi có người thân ốm đau?",
  "Tài Chính Cá Nhân Trong Tình Huống Khẩn Cấp",
  "Làm thế nào để chuẩn bị tài chính cho tình huống khẩn cấp?",
  "Làm thế nào để xây dựng quỹ khẩn cấp?",
  "Làm thế nào để duy trì quỹ khẩn cấp?",
  "Khi nào nên sử dụng quỹ khẩn cấp?",
  "Làm thế nào để tái tạo quỹ khẩn cấp sau khi đã sử dụng?",
  "Làm thế nào để quản lý tài chính trong thời gian thất nghiệp?",
  "Làm thế nào để chuẩn bị tài chính cho bệnh tật hoặc tai nạn?",
  "Làm thế nào để quản lý tài chính khi mất thu nhập đột ngột?",
  "Làm thế nào để lập kế hoạch tài chính cho việc sửa chữa nhà cửa đột xuất?",
  "Làm thế nào để lập kế hoạch tài chính cho việc mua sắm thiết bị gia đình khẩn cấp?",
  "Tài Chính Cá Nhân Trong Mối Quan Hệ",
  "Làm thế nào để quản lý tài chính trong hôn nhân?",
  "Làm thế nào để lập ngân sách chung cho vợ chồng?",
  "Làm thế nào để quản lý tài chính khi có con cái?",
  "Làm thế nào để tiết kiệm tiền cho tương lai của con cái?",
  "Làm thế nào để quản lý tài chính khi ly hôn?",
  "Làm thế nào để lập kế hoạch tài chính cho việc nuôi dưỡng con cái?",
  "Làm thế nào để bảo vệ tài chính gia đình khi một người qua đời?",
  "Làm thế nào để quản lý tài chính khi chăm sóc người già?",
  "Làm thế nào để lập kế hoạch tài chính cho việc chăm sóc người thân bệnh tật?",
  "Làm thế nào để chia sẻ trách nhiệm tài chính trong gia đình?",
  "Tài Chính Cá Nhân Trong Kinh Doanh",
  "Làm thế nào để quản lý tài chính cá nhân khi làm chủ doanh nghiệp?",
  "Làm thế nào để lập kế hoạch tài chính cho doanh nghiệp nhỏ?",
  "Làm thế nào để tiết kiệm tiền trong kinh doanh?",
  "Làm thế nào để quản lý nợ của doanh nghiệp?",
  "Làm thế nào để đầu tư vào doanh nghiệp nhỏ?",
  "Làm thế nào để lập kế hoạch tài chính cho việc mở rộng kinh doanh?",
  "Làm thế nào để quản lý tài chính khi kinh doanh gặp khó khăn?",
  "Làm thế nào để lập kế hoạch tài chính cho việc khởi nghiệp?",
  "Làm thế nào để quản lý tài chính khi có đối tác kinh doanh?",
  "Làm thế nào để bảo vệ tài chính cá nhân khi kinh doanh thất bại?",
  "Chiến Lược Tiết Kiệm",
  "Làm thế nào để tiết kiệm tiền hàng tháng một cách hiệu quả?",
  "Làm thế nào để tiết kiệm tiền khi mua sắm?",
  "Làm thế nào để tiết kiệm tiền khi đi du lịch?",
  "Làm thế nào để tiết kiệm tiền khi ăn uống ngoài nhà?",
  "Làm thế nào để tiết kiệm tiền khi mua sắm trực tuyến?",
  "Làm thế nào để tiết kiệm tiền khi mua sắm thiết bị gia đình?",
  "Làm thế nào để tiết kiệm tiền khi mua sắm quần áo?",
  "Làm thế nào để tiết kiệm tiền khi mua xe hơi?",
  "Làm thế nào để tiết kiệm tiền khi sửa chữa nhà cửa?",
  "Làm thế nào để tiết kiệm tiền khi tổ chức sự kiện?",
  "Quản Lý Chi Phí",
  "Làm thế nào để theo dõi chi phí hàng tháng?",
  "Làm thế nào để phân loại chi phí hàng tháng?",
  "Làm thế nào để cắt giảm chi phí không cần thiết?",
  "Làm thế nào để duy trì chi phí hàng tháng trong ngân sách?",
  "Làm thế nào để điều chỉnh chi phí khi thu nhập thay đổi?",
  "Làm thế nào để lập kế hoạch chi phí cho kỳ nghỉ?",
  "Làm thế nào để lập kế hoạch chi phí cho sự kiện đặc biệt?",
  "Làm thế nào để quản lý chi phí giáo dục của con cái?",
  "Làm thế nào để quản lý chi phí chăm sóc sức khỏe?",
  "Làm thế nào để lập kế hoạch chi phí cho việc mua sắm lớn?",
  "Tài Chính Cá Nhân Trong Từng Giai Đoạn Cuộc Đời",
  "Làm thế nào để quản lý tài chính khi mới ra trường?",
  "Làm thế nào để lập kế hoạch tài chính khi kết hôn?",
  "Làm thế nào để tiết kiệm tiền khi có con nhỏ?",
  "Làm thế nào để quản lý tài chính khi mua nhà?",
  "Làm thế nào để lập kế hoạch tài chính khi ly hôn?",
  "Làm thế nào để quản lý tài chính khi có người thân ốm đau?",
  "Làm thế nào để lập kế hoạch tài chính khi nghỉ hưu?",
  "Làm thế nào để bảo vệ tài chính cá nhân khi nghỉ hưu?",
  "Làm thế nào để lập kế hoạch tài chính cho tuổi già?",
  "Làm thế nào để quản lý tài chính khi chăm sóc người già?",
  "Tài Chính Cá Nhân Trong Môi Trường Kỹ Thuật Số",
  "Làm thế nào để bảo vệ tài chính cá nhân trực tuyến?",
  "Làm thế nào để quản lý tài chính cá nhân bằng ứng dụng di động?",
  "Làm thế nào để tiết kiệm tiền khi mua sắm trực tuyến?",
  "Làm thế nào để bảo vệ thông tin tài chính cá nhân trực tuyến?",
  "Làm thế nào để sử dụng ngân hàng trực tuyến một cách an toàn?",
  "Những lỗi phổ biến khi quản lý tài chính trực tuyến là gì?",
  "Làm thế nào để quản lý chi tiêu trực tuyến?",
  "Làm thế nào để lập kế hoạch tài chính trực tuyến?",
  "Làm thế nào để tối ưu hóa thuế trực tuyến?",
  "Làm thế nào để đầu tư trực tuyến một cách an toàn?",
  "Tài Chính Cá Nhân Trong Các Tình Huống Đặc Biệt",
  "Làm thế nào để quản lý tài chính khi bị thất nghiệp?",
  "Làm thế nào để lập kế hoạch tài chính khi ly hôn?",
  "Làm thế nào để quản lý tài chính khi bị bệnh tật?",
  "Làm thế nào để lập kế hoạch tài chính khi có người thân qua đời?",
  "Làm thế nào để bảo vệ tài chính cá nhân khi gặp khó khăn tài chính?",
  "Làm thế nào để lập kế hoạch tài chính khi chuyển nhà?",
  "Làm thế nào để quản lý tài chính khi bị thiên tai?",
  "Làm thế nào để lập kế hoạch tài chính khi di cư?",
  "Làm thế nào để bảo vệ tài chính cá nhân khi gặp khủng hoảng kinh tế?",
  "Làm thế nào để lập kế hoạch tài chính khi có sự thay đổi lớn trong cuộc sống?",
  "Hy vọng danh sách này sẽ giúp bạn có cái nhìn tổng quan và cung cấp nội dung phong phú để tư vấn cho khách hàng về tài chính cá nhân.",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho các loại chi phí khác nhau?",
  "Hôm qua tôi đã tiết kiệm được bao nhiêu tiền?",
  "Hôm qua tổng thu nhập của tôi là bao nhiêu?",
  "Hôm qua có bao nhiêu giao dịch được thực hiện?",
  "Hôm qua tôi đã chi tiêu nhiều nhất vào mục nào?",
  "Hôm qua tôi đã chi tiêu ít nhất vào mục nào?",
  "Hôm qua tỷ lệ giữa thu nhập và chi tiêu của tôi là bao nhiêu?",
  "Hôm qua số tiền nợ của tôi là bao nhiêu?",
  "Hôm qua số tiền tôi đầu tư là bao nhiêu?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho giải trí và du lịch?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho các dịch vụ tiện ích?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho chăm sóc sức khỏe?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho việc mua sắm?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho việc giáo dục?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho bảo dưỡng và sửa chữa ô tô?",
  "Hôm qua có bao nhiêu giao dịch không cần thiết được thực hiện?",
  "Hôm qua số tiền tôi chi cho các hoạt động từ thiện là bao nhiêu?",
  "Hôm qua số tiền tôi chi tiêu cho thuê nhà hoặc trả góp là bao nhiêu?",
  "Hôm qua số tiền tôi chi tiêu cho chăm sóc thú cưng là bao nhiêu?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho các khoản vay và trả góp?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho việc chuyển tiền cho người thân hoặc bạn bè?",
  "Hôm qua số tiền tôi chi tiêu cho các món quà là bao nhiêu?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho các sự kiện đặc biệt (tiệc, sinh nhật, v.v.)?",
  "Hôm qua tổng số tiền thu nhập từ các nguồn khác nhau là bao nhiêu?",
  "Hôm qua tôi đã chi bao nhiêu cho việc thanh toán hóa đơn?",
  "Hôm qua số tiền tôi chi tiêu cho việc bảo trì thiết bị gia đình là bao nhiêu?",
  "Hôm qua số tiền tôi chi tiêu cho việc rút tiền mặt từ ATM là bao nhiêu?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho các khoản chi tiêu bất thường?",
  "Hôm qua tổng số giao dịch thẻ tín dụng của tôi là bao nhiêu?",
  "Hôm qua tôi đã chi tiêu bao nhiêu cho việc bảo hiểm?",
];

export const categoryQuestion = {
  "Quản lý tài chính cá nhân": [
    "Số dư hiện tại trong tài khoản của tôi là bao nhiêu?",
    "Tôi đã chi tiêu bao nhiêu trong tháng này?",
    "Có bao nhiêu tiền đã được chuyển vào tài khoản của tôi trong tuần qua?",
    "Tôi có những giao dịch nào trong ngày hôm nay?",
    "Lịch sử giao dịch của tôi trong tháng trước như thế nào?",
    "Số dư tài khoản của tôi đã thay đổi như thế nào trong tuần qua?",
    "Tôi đã thanh toán hóa đơn nào trong tháng này?",
    "Có giao dịch nào đang chờ xử lý không?",
    "Tôi có bao nhiêu tiền trong tài khoản tiết kiệm?",
    "Tôi có những khoản vay nào chưa thanh toán?",
    "Tôi đã nhận được những khoản thu nào trong tháng này?",
    "Tôi đã tiêu tiền vào những mục gì trong tháng trước?",
    "Tài khoản của tôi có bị trừ phí dịch vụ nào không?",
    "Số dư tối thiểu cần duy trì trong tài khoản của tôi là bao nhiêu?",
    "Tôi có bao nhiêu tiền mặt khả dụng để rút?",
    "Lãi suất hiện tại cho tài khoản tiết kiệm của tôi là bao nhiêu?",
    "Tôi có bao nhiêu tài khoản liên kết với chatbot này?",
    "Lịch sử giao dịch của tôi trong năm nay như thế nào?",
    "Tôi đã chuyển tiền cho ai trong tuần qua?",
    "Có khoản thanh toán tự động nào sắp diễn ra không?",
    "Tôi có bao nhiêu khoản thu nhập cố định mỗi tháng?",
    "Tôi đã tiết kiệm được bao nhiêu tiền trong năm nay?",
    "Tôi đã chi tiêu bao nhiêu cho mua sắm trong tháng này?",
    "Tôi đã thanh toán hóa đơn điện nước chưa?",
    "Số dư trong thẻ tín dụng của tôi là bao nhiêu?",
    "Tôi có khoản tiền gửi nào đang chờ giải ngân không?",
    "Tôi có bao nhiêu khoản chi tiêu định kỳ?",
    "Lịch sử thanh toán thẻ tín dụng của tôi như thế nào?",
    "Có giao dịch nào bị từ chối không?",
    "Tôi đã tiết kiệm được bao nhiêu trong tháng trước?",
  ],
  "Gợi ý chi tiêu và đầu tư": [
    "Tôi nên đầu tư vào loại hình nào để sinh lời tốt nhất?",
    "Làm thế nào để tôi có thể tiết kiệm nhiều hơn mỗi tháng?",
    "Tôi có nên đầu tư vào cổ phiếu không?",
    "Gợi ý cách quản lý chi tiêu hiệu quả cho tôi.",
    "Tôi có thể tối ưu hóa danh mục đầu tư của mình như thế nào?",
    "Có nên đầu tư vào bất động sản không?",
    "Tôi nên dành bao nhiêu phần trăm thu nhập để tiết kiệm?",
    "Gợi ý cho tôi một kế hoạch đầu tư dài hạn.",
    "Làm thế nào để giảm chi phí sinh hoạt hàng tháng?",
    "Tôi có nên đầu tư vào quỹ tương hỗ không?",
    "Tôi nên chia tiền tiết kiệm như thế nào giữa các tài khoản?",
    "Có nên đầu tư vào tiền điện tử không?",
    "Gợi ý cho tôi một kế hoạch chi tiêu hàng tháng.",
    "Làm thế nào để theo dõi chi tiêu hàng ngày hiệu quả?",
    "Tôi nên đầu tư vào cổ phiếu nào trong năm nay?",
    "Tôi có nên mở tài khoản tiết kiệm có kỳ hạn không?",
    "Có ứng dụng nào giúp quản lý tài chính cá nhân hiệu quả?",
    "Tôi nên ưu tiên trả hết nợ trước hay bắt đầu đầu tư?",
    "Gợi ý cho tôi một chiến lược đầu tư an toàn.",
    "Làm thế nào để quản lý tài chính khi có nhiều nguồn thu nhập?",
    "Tôi nên đầu tư vào ngành công nghiệp nào hiện nay?",
    "Tôi có nên tham gia vào các chương trình tiết kiệm của ngân hàng không?",
    "Gợi ý cho tôi một phương pháp tiết kiệm hiệu quả.",
    "Làm thế nào để cắt giảm chi phí không cần thiết?",
    "Tôi có nên đầu tư vào chứng khoán phái sinh không?",
    "Tôi nên tiết kiệm bao nhiêu phần trăm thu nhập hàng tháng?",
    "Gợi ý cho tôi một kế hoạch tài chính cho hưu trí.",
    "Tôi có nên đầu tư vào các công ty khởi nghiệp không?",
    "Làm thế nào để tôi có thể kiểm soát chi tiêu khi đi du lịch?",
    "Tôi nên đầu tư vào các dự án xanh không?",
  ],
  "Cảnh báo thu chi bất thường": [
    "Có giao dịch nào bất thường trong tài khoản của tôi không?",
    "Tôi có khoản chi nào lớn bất thường trong tháng này không?",
    "Có khoản thu nhập nào bất thường không?",
    "Tại sao số dư tài khoản của tôi giảm đột ngột?",
    "Có giao dịch nào bị nghi ngờ là gian lận không?",
    "Tôi có khoản chi nào vượt quá ngân sách không?",
    "Tại sao tôi bị trừ tiền mà không rõ lý do?",
    "Có khoản chi nào không nằm trong kế hoạch của tôi không?",
    "Tôi có nhận được khoản tiền nào từ nguồn không rõ không?",
    "Có giao dịch quốc tế nào trong tài khoản của tôi không?",
    "Tôi có khoản chi nào trùng lặp không?",
    "Có giao dịch nào diễn ra vào giờ bất thường không?",
    "Tại sao tôi lại bị trừ phí dịch vụ cao hơn thường lệ?",
    "Có khoản chi nào không khớp với hóa đơn của tôi không?",
    "Có giao dịch nào diễn ra từ thiết bị không nhận diện không?",
    "Tôi có bị trừ phí giao dịch quốc tế không?",
    "Có khoản thu nhập nào không khớp với nguồn thu của tôi không?",
    "Tôi có bị tính phí lãi suất cao hơn không?",
    "Có giao dịch nào không nằm trong khu vực tôi sống không?",
    "Tôi có khoản chi nào liên quan đến các trang web lạ không?",
    "Tại sao tôi bị trừ tiền cho dịch vụ tôi không đăng ký?",
    "Có giao dịch nào liên quan đến các nền tảng trực tuyến không quen thuộc không?",
    "Tôi có khoản chi nào liên quan đến các ứng dụng di động lạ không?",
    "Có giao dịch nào bị hủy mà không có lý do rõ ràng không?",
    "Tôi có bị trừ tiền cho giao dịch không thành công không?",
    "Có giao dịch nào bị từ chối mà tôi không thực hiện không?",
    "Tôi có bị trừ tiền cho các giao dịch thử nghiệm không?",
    "Có khoản chi nào liên quan đến các dịch vụ giải trí lạ không?",
    "Tại sao tôi bị trừ tiền cho các dịch vụ tôi đã hủy?",
    "Có giao dịch nào diễn ra ngoài giờ làm việc của tôi không?",
  ],
  "Tạo biểu đồ thống kê": [
    "Hãy tạo biểu đồ chi tiêu hàng tháng của tôi.",
    "Tạo biểu đồ so sánh thu nhập và chi tiêu hàng tháng.",
    "Tạo biểu đồ xu hướng tiết kiệm của tôi trong năm nay.",
    "Tôi muốn xem biểu đồ phân bổ chi tiêu theo các danh mục.",
    "Tạo biểu đồ so sánh chi tiêu của tôi theo các tuần trong tháng này.",
    "Biểu đồ số dư tài khoản của tôi thay đổi theo thời gian như thế nào?",
    "Tôi muốn xem biểu đồ phân tích chi tiêu cho giải trí.",
    "Tạo biểu đồ tổng hợp các khoản thu nhập của tôi trong năm nay.",
    "Biểu đồ chi tiêu cho mua sắm của tôi như thế nào trong tháng trước?",
    "Tạo biểu đồ so sánh chi tiêu hàng tháng của tôi trong năm nay.",
    "Tôi muốn xem biểu đồ tiết kiệm hàng tháng của tôi.",
    "Tạo biểu đồ xu hướng chi tiêu của tôi theo các năm.",
    "Tạo biểu đồ phân tích chi tiêu cho các khoản vay.",
    "Biểu đồ chi tiêu cho ăn uống của tôi như thế nào trong tháng này?",
    "Tạo biểu đồ so sánh các khoản thu nhập của tôi theo các quý.",
    "Tôi muốn xem biểu đồ phân tích chi tiêu cho du lịch.",
    "Tạo biểu đồ so sánh chi tiêu của tôi cho các hoạt động giải trí.",
    "Biểu đồ chi tiêu cho giáo dục của tôi như thế nào trong năm nay?",
    "Tạo biểu đồ xu hướng chi tiêu cho sức khỏe của tôi.",
    "Tạo biểu đồ phân tích chi tiêu cho các dịch vụ tiện ích.",
    "Biểu đồ chi tiêu cho vận chuyển của tôi như thế nào trong tháng trước?",
    "Tạo biểu đồ so sánh chi tiêu hàng ngày của tôi trong tuần qua.",
    "Tôi muốn xem biểu đồ phân tích chi tiêu cho gia đình.",
    "Tạo biểu đồ xu hướng chi tiêu cho các dịch vụ trực tuyến của tôi.",
    "Biểu đồ chi tiêu cho nhà ở của tôi như thế nào trong năm nay?",
    "Tạo biểu đồ so sánh chi tiêu của tôi cho các hoạt động từ thiện.",
    "Tôi muốn xem biểu đồ phân tích chi tiêu cho các hoạt động thể thao.",
    "Tạo biểu đồ xu hướng chi tiêu của tôi theo các tháng trong năm.",
    "Biểu đồ chi tiêu cho các dịch vụ cá nhân của tôi như thế nào?",
    "Tạo biểu đồ so sánh chi tiêu của tôi cho các sự kiện xã hội.",
  ],
};
