name: Deploy to Amazon ECS

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    name: CI Pipeline
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TAG: ${{ github.sha }}

  cd:
    name: CD Pipeline
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOSTNAME }} > ~/.ssh/known_hosts

      # - name: connect and pull
      #   run: ssh ${{ secrets.USER_NAME }}@${{ secrets.HOSTNAME }} "cd goldenowl-devops-internship-challenge && bash deploy.sh ${{ github.sha }}"

      # - name: cleanup
      #   run: rm -rf ~/.ssh
